/* Copyright 2019 Thomas Baart <thomas@splitkb.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#include QMK_KEYBOARD_H

#if __has_include("keymap.h")
#    include "keymap.h"
#endif

enum layers {
    _QWERTY,
    _NAVIGATION,
    _NUMPAD,
    _SYMBOLS,
    _FUNCTIONS,
    _ADJUST,
};

// Aliases for changing layers
#define NAV MO(_NAVIGATION)
#define NUMS MO(_NUMPAD)
#define SYMBS MO(_SYMBOLS)
#define FUNCS MO(_FUNCTIONS)
#define ADJS MO(_ADJUST)
#define NUM_TAB LT(_NUMPAD, KC_TAB)
#define QUO_FUN LT(_FUNCTIONS, KC_QUOT)

// Aliases for modifiers
#define LCAPS SFT_T(KC_CAPS)
#define RCAPS RSFT_T(KC_CAPS)

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    /*
     * 1st layer -> QWERTY
     *
     * ,-----------------------------------------.                    ,-----------------------------------------.
     * |      |   1  |   2  |   3  |   4  |   5  |                    |   6  |   7  |   8  |   9  |   0  |      |
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * | ESC  |   Q  |   W  |   E  |   R  |   T  |                    |   Y  |   U  |   I  |   O  |   P  |BACKSP|
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * |NUMTAB|   A  |   S  |   D  |   F  |   G  |                    |   H  |   J  |   K  |   L  |   ;  |QUOFUN|
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * |LCAPS |   Z  |   X  |   C  |   V  |   B  |-------|    |-------|   N  |   M  |   ,  |   .  |   /  |RCAPS |
     * `-----------------------------------------/      /      \      \-----------------------------------------'
     *                          |LCTRL | NAV  | /Space /        \Enter \  |SYMBS | LALT |
     *                          |      |      |/      /          \      \ |      |      |
     *                          `--------------------'            '------''-------------'
     */
    [_QWERTY] = LAYOUT(
        XXXXXXX,    KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                        KC_6,    KC_7,    KC_8,    KC_9,    KC_0, XXXXXXX,
         KC_ESC,    KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,                        KC_Y,    KC_U,    KC_I,    KC_O,    KC_P, KC_BSPC,
        NUM_TAB,    KC_A,    KC_S,    KC_D,    KC_F,    KC_G,                        KC_H,    KC_J,    KC_K,    KC_L, KC_SCLN, QUO_FUN,
          LCAPS,    KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,                        KC_N,    KC_M, KC_COMM,  KC_DOT, KC_SLSH,   RCAPS,
                                            KC_LCTL,     NAV,  KC_SPC,    KC_ENT,   SYMBS, KC_LALT
    ),

    /*
     * 2nd layer -> Navigation
     *
     * ,-----------------------------------------.                    ,-----------------------------------------.
     * |      |   1  |   2  |   3  |   4  |   5  |                    |   6  |   7  |   8  |   9  |   0  |      |
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * | ESC  |      |      |      |      |      |                    |      |      |  Up  |      |      |BACKSP|
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * |NUMTAB|      |LCTRL | LALT |LSHIFT|      |                    | Home | Left | Down |Right | End  | DEL  |
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * |LCAPS |      |      | META | MENU |      |-------|    |-------|      |      |      |      |      |RCAPS |
     * `-----------------------------------------/      /      \      \-----------------------------------------'
     *                          | ADJ  |      | /Space /        \Enter \  | DEL  |BACKSP|
     *                          |      |      |/      /          \      \ |      |      |
     *                          `--------------------'            '------''-------------'
     */
    [_NAVIGATION] = LAYOUT(
        XXXXXXX,    KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                        KC_6,    KC_7,    KC_8,    KC_9,    KC_0, XXXXXXX,
        _______, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_PSCR,                     XXXXXXX, XXXXXXX,   KC_UP, XXXXXXX, XXXXXXX, _______,
        _______, XXXXXXX, KC_LCTL, KC_LALT, KC_LSFT, XXXXXXX,                     KC_HOME, KC_LEFT, KC_DOWN, KC_RGHT,  KC_END,  KC_DEL,
        _______, XXXXXXX, XXXXXXX, KC_LGUI,  KC_APP, XXXXXXX,                     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, _______,
                                               ADJS, XXXXXXX, _______,   _______,  KC_DEL, KC_BSPC
    ),

    /*
     * 3rd layer -> Numpad
     *
     * ,-----------------------------------------.                    ,-----------------------------------------.
     * |      |      |      |      |      |      |                    |      |      |      |      |      |      |
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * | ESC  |      |      |    - |    + |    = |                    |      |    7 |    8 |    9 |      |BACKSP|
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * |      |      |      |    * |    / |    % |                    |      |    4 |    5 |    6 |      | DEL  |
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * |LCAPS |      |      |    ^ |    , |    . |-------|    |-------|      |    1 |    2 |    3 |      |RCAPS |
     * `-----------------------------------------/      /      \      \-----------------------------------------'
     *                          |      |      | /Space /        \Enter \  |    0 |    . |
     *                          |      |      |/      /          \      \ |      |      |
     *                          `--------------------'            '------''-------------'
     */
    [_NUMPAD] = LAYOUT(
        _______, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, _______,
        _______, XXXXXXX, XXXXXXX, KC_MINS, KC_PLUS,  KC_EQL,                     XXXXXXX,    KC_7,    KC_8,    KC_9, XXXXXXX, _______,
        _______, XXXXXXX, XXXXXXX, KC_ASTR, KC_PSLS, KC_PERC,                     XXXXXXX,    KC_4,    KC_5,    KC_6, XXXXXXX,  KC_DEL,
        _______, XXXXXXX, XXXXXXX, KC_CIRC, KC_COMM,  KC_DOT,                     XXXXXXX,    KC_1,    KC_2,    KC_3, XXXXXXX, _______,
                                            XXXXXXX, XXXXXXX, _______,   _______,    KC_0,  KC_DOT
    ),


    /*
     * 4rd layer -> Symbols
     *
     * ,-----------------------------------------.                    ,-----------------------------------------.
     * |      |      |      |      |      |      |                    |      |      |      |      |      |      |
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * | ESC  |      |      |    ( |    ) |    # |                    |    ! |    & |    | |    \ |      |BACKSP|
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * |      |      |      |    { |    } |    @ |                    |    $ |    = |    - |    _ |   `  | DEL  |
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * |LCAPS |      |      |    [ |    ] |      |-------|    |-------|    + |    - |    < |    > |    ~ |    ? |
     * `-----------------------------------------/      /      \      \-----------------------------------------'
     *                          |      |      | /SPACE /        \ENTER \  |      |      |
     *                          |      |      |/      /          \      \ |      |      |
     *                          `--------------------'            '------''-------------'
     */
    [_SYMBOLS] = LAYOUT(
        _______, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        _______, XXXXXXX, XXXXXXX, KC_LPRN, KC_RPRN, KC_HASH,                     KC_EXLM, KC_AMPR, KC_PIPE, KC_PSLS, KC_BSLS, _______,
        _______, XXXXXXX, XXXXXXX, KC_LCBR, KC_RCBR,   KC_AT,                      KC_DLR,  KC_EQL, KC_PMNS, KC_UNDS,  KC_GRV,  KC_DEL,
        _______, XXXXXXX, XXXXXXX, KC_LBRC, KC_RBRC, XXXXXXX,                     KC_PLUS,KC_MINUS, KC_LABK, KC_RABK, KC_TILD, KC_QUES,
                                            XXXXXXX, XXXXXXX, _______,   _______, XXXXXXX, XXXXXXX
    ),

    /*
     * 5th layer -> Functions
     *
     * ,-----------------------------------------.                    ,-----------------------------------------.
     * |      |      |      |      |      |      |                    |      |      |      |      |      |      |
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * | ESC  |      |      |      |      |      |                    |      |   F9 |  F10 |  F11 |  F12 |BACKSP|
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * |      |      |LCTRL | LALT |LSHIFT|      |                    |      |   F5 |   F6 |   F7 |   F8 | DEL  |
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * |LCAPS |      |      |      |      |      |-------|    |-------|      |   F1 |   F2 |   F3 |   F4 |      |
     * `-----------------------------------------/      /      \      \-----------------------------------------'
     *                          |      |      | /SPACE /        \ENTER \  |      |      |
     *                          |      |      |/      /          \      \ |      |      |
     *                          `--------------------'            '------''-------------'
     */
    [_FUNCTIONS] = LAYOUT(
        _______, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        _______, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                     XXXXXXX,   KC_F9,  KC_F10,  KC_F11,  KC_F12, _______,
        _______, XXXXXXX, KC_LCTL, KC_LALT, KC_LSFT, XXXXXXX,                     XXXXXXX,   KC_F5,   KC_F6,   KC_F7,   KC_F8, KC_DEL,
        _______, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                     XXXXXXX,   KC_F1,   KC_F2,   KC_F3,   KC_F4, _______,
                                            XXXXXXX, XXXXXXX, _______,   _______, XXXXXXX, XXXXXXX
    ),

    /*
     * 6th layer -> Adjust
     *
     * ,-----------------------------------------.                    ,-----------------------------------------.
     * |      |      |      |      |      |      |                    |      |      |      |      |      |      |
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * | ESC  |      |      |      |      |      |                    |      |      |      |      |      |      |
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * |      |      |      |      |      |      |                    |      |      |RGB ON| HUE+ | SAT+ | VAL+ |
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * |      |      |      |      |      |      |-------|    |-------|      |      | MODE | HUE- | SAT- | VAL- |
     * `-----------------------------------------/      /      \      \-----------------------------------------'
     *                          |      |      | /SPACE /        \ENTER \  |      |      |
     *                          |      |      |/      /          \      \ |      |      |
     *                          `--------------------'            '------''-------------'
     */
    [_ADJUST] = LAYOUT(
        _______, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        _______, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                     XXXXXXX, XXXXXXX, UG_TOGG, UG_HUEU, UG_SATU, UG_VALU,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                     XXXXXXX, XXXXXXX, UG_NEXT, UG_HUED, UG_SATD, UG_VALD,
                                            XXXXXXX, XXXXXXX, _______,   _______, XXXXXXX, XXXXXXX
    )
 };
